version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../frontend/dist:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro

    depends_on:
      - spring

  spring:
    build: .
    container_name: spring
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}

      # MySQL
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

      # JPA
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}

      # AWS S3
      CLOUD_AWS_S3_BUCKET: ${CLOUD_AWS_S3_BUCKET}
      CLOUD_AWS_CREDENTIALS_ACCESS_KEY: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      CLOUD_AWS_CREDENTIALS_SECRET_KEY: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
      CLOUD_AWS_REGION_STATIC: ${CLOUD_AWS_REGION_STATIC}

      # Redis
      SPRING_DATA_REDIS_HOST1: ${SPRING_DATA_REDIS_HOST1}
      SPRING_DATA_REDIS_HOST2: ${SPRING_DATA_REDIS_HOST2}
      SPRING_DATA_REDIS_HOST3: ${SPRING_DATA_REDIS_HOST3}
      SPRING_DATA_REDIS_PASSWORD: ${SPRING_DATA_REDIS_PASSWORD}
      SPRING_DATA_REDIS_PORT_REDIS1: ${SPRING_DATA_REDIS_PORT_REDIS1}
      SPRING_DATA_REDIS_PORT_REDIS2: ${SPRING_DATA_REDIS_PORT_REDIS2}
      SPRING_DATA_REDIS_PORT_REDIS3: ${SPRING_DATA_REDIS_PORT_REDIS3}

      # Web3Auth
      WEB3AUTH_JWKS_URL: ${WEB3AUTH_JWKS_URL}

      # JWT
      JWT_SECRET: ${JWT_SECRET}

      # Selenium
      SELENIUM_REMOTE_URLS: ${SELENIUM_REMOTE_URLS}

      # stadium
      STADIUM_URL: ${STADIUM_URL}

      # admin
      ADMIN_PRIVATE_KEY: ${ADMIN_PRIVATE_KEY}

  selenium-chrome-1:
    image: selenium/standalone-chrome:134.0-20250323
    container_name: selenium-chrome-1
    ports:
      - "4444:4444"
      - "5900:5900"
    shm_size: 1g
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_MAX_INSTANCES=2

  selenium-chrome-2:
    image: selenium/standalone-chrome:134.0-20250323
    container_name: selenium-chrome-2
    ports:
      - "4445:4444"
      - "5901:5900"
    shm_size: 1g
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_MAX_INSTANCES=2

  selenium-chrome-3:
    image: selenium/standalone-chrome:134.0-20250323
    container_name: selenium-chrome-3
    ports:
      - "4446:4444"
      - "5902:5900"
    shm_size: 1g
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_MAX_INSTANCES=2

  selenium-chrome-4:
    image: selenium/standalone-chrome:134.0-20250323
    container_name: selenium-chrome-4
    ports:
      - "4447:4444"
      - "5903:5900"
    shm_size: 1g
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_MAX_INSTANCES=2
      -
  selenium-chrome-5:
    image: selenium/standalone-chrome:134.0-20250323
    container_name: selenium-chrome-5
    ports:
      - "4448:4444"
      - "5904:5900"
    shm_size: 1g
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_MAX_INSTANCES=2